services:
  actions-runner:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      RUNNER_USER: ${RUNNER_USER}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Expose Docker socket
